### PR TITLE
update duckdb file to 0.7.x

### PR DESCRIPTION
**Pull request by gregwdata**
Creating a draft PR addressing #35.

This has the same `needful_things.duckdb` file as updated in  https://github.com/evidence-dev/evidence/pull/654 . That file was created with duckdb 0.7.0, and I have verified that 0.7.1 reads the file without error.

Made a guess at what the new evidence version # will be in the `package.json`. 

Awaiting release of new evidence version incorporating https://github.com/evidence-dev/evidence/pull/654, then will install to update `package-lock.json` and finalize PR.

### CODE REVIEW

**Comment by gregwdata** [comment]
Tested with Evidence 14.0.0. It connects to the updated DuckDB file and renders the query results and plot:
image

I included the `--open` flag in the dev command, following https://github.com/evidence-dev/template/pull/37

**Comment by archiewood** [comment]
Sweet!

**Comment by archiewood** [comment]
Hmm this is not working on my machine  or in codespace

**Comment by archiewood** [comment]
Might make sense to grab the duckdb file from this PR and stick it into #37

**Comment by gregwdata** [comment]
> Might make sense to grab the duckdb file from this PR and stick it into #37

If that works for you, sounds good! Feel free to close this one. 

I was testing on codespaces, with `npm run dev -- --host=0.0.0.0`. I did run `npm update` before running, on that codespaces instance, after first installing with a 13.x.x release. Maybe that factors in.

**Comment by archiewood** [comment]
closed by #37

**Pull request closed without merging**
